# Generated by Django 3.0.7 on 2020-06-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='postsno',
            new_name='post',
        ),
    ]
