# Generated by Django 3.0.7 on 2020-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200623_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewip',
            field=models.CharField(default='127.0.0.1', max_length=16),
            preserve_default=False,
        ),
    ]
