# Generated by Django 3.0.7 on 2020-06-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_viewip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewip',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
