# Generated by Django 3.0.7 on 2020-06-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200623_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('ipaddr', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
