# Generated by Django 2.2 on 2020-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='viewsno',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postview',
            name='ipaddr',
            field=models.CharField(max_length=15),
        ),
    ]
